apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

components:
  - ../../../../components/networkpolicy/deny-all
  - ../../../../components/networkpolicy/allow-dns
  - ../../../../components/networkpolicy/allow-kube-api
  - ../../../../components/networkpolicy/allow-internal
  - ../../../../components/networkpolicy/allow-1password-connect

resources:
  - allow-dns.yaml
