---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-cloudflare
  namespace: networking
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      external-dns-cloudflare:
        containers:
          app:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.19.0
            args:
              - --provider=cloudflare
              - --domain-filter=${SECRET_DOMAIN}
              - --zone-id-filter=$(CF_ZONE_ID)
              - --cloudflare-proxied
              - --registry=txt
              - --txt-owner-id=k8s-${CLUSTER}-public
              - --txt-prefix=${EXTERNALDNS_TXT_PREFIX}
              - --source=gateway-httproute
              - --gateway-name=${CILIUM_GATEWAY_EXTERNAL_NAME}
              - --controller-id=${CLUSTER}-public
              - --interval=${EXTERNALDNS_INTERVAL}
              - --log-format=text
              - --log-level=${EXTERNALDNS_LOG_LEVEL}
            envFrom:
              - secretRef:
                  name: external-dns-cloudflare-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
    serviceAccount:
      create: false
      name: external-dns-cloudflare
    service:
      app:
        controller: external-dns-cloudflare
        ports:
          http:
            port: 7979
    serviceMonitor:
      app:
        serviceName: external-dns-cloudflare
        endpoints:
          - port: http
