---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: victoria-metrics-vmcluster
  namespace: flux-system
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - externalsecret.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - prometheusrule.yaml
  - ../../dashboards
commonLabels:
  app.kubernetes.io/name: victoria-metrics
  app.kubernetes.io/component: vmcluster
  app.kubernetes.io/managed-by: flux
