---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
  namespace: flux-system
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/component: vmcluster
spec:
  interval: 12h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    tag: "${VICTORIAMETRICS_K8S_STACK_VERSION}"  # 0.61.11
