---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: victoria-logs
  namespace: flux-system
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - servicemonitor.yaml
commonLabels:
  app.kubernetes.io/name: victoria-logs
  app.kubernetes.io/managed-by: flux
