---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-single
  labels:
    app.kubernetes.io/name: victoria-logs
spec:
  interval: 12h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  ref:
    tag: "0.11.12"  # Exact version pinning
