---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg/operator/ks.yaml
  - cloudnative-pg/shared-cluster/ks.yaml
  - dragonfly-operator/ks.yaml
  - ../workloads/platform/databases/dragonfly/ks.yaml
