---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluent-bit

resources:
  - namespace.yaml
  - ocirepository.yaml
  - helmrelease.yaml

labels:
  - pairs:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: observability
      app.kubernetes.io/managed-by: flux
