apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fluent-bit-operator
  namespace: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: flux

resources:
  - namespace.yaml
  - ocirepository.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/name: fluent-bit
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: logging
  app.kubernetes.io/managed-by: flux

commonAnnotations:
  config.kubernetes.io/origin: bases/fluent-bit-operator/operator