---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: fluent-bit
  namespace: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: helm-chart
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/fluent-bit
  ref:
    tag: "0.54.0"
  verify:
    provider: cosign
