---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-rfc2136
  namespace: networking
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 1h
  values:
    controllers:
      external-dns-rfc2136:
        containers:
          app:
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.19.0
            args:
              - --provider=rfc2136
              - --rfc2136-host=$(RFC2136_HOST)
              - --rfc2136-port=$(RFC2136_PORT)
              - --rfc2136-zone=$(RFC2136_ZONE)
              - --rfc2136-tsig-keyname=$(RFC2136_TSIG_KEYNAME)
              - --rfc2136-tsig-secret=$(RFC2136_TSIG_SECRET)
              - --rfc2136-tsig-secret-alg=$(RFC2136_TSIG_ALG)
              - --rfc2136-tsig-axfr
              - --domain-filter=${SECRET_DOMAIN}
              - --registry=txt
              - --txt-owner-id=k8s-${CLUSTER}-private
              - --txt-prefix=${EXTERNALDNS_TXT_PREFIX}
              - --source=gateway-httproute
              - --gateway-name=${CILIUM_GATEWAY_INTERNAL_NAME}
              - --controller-id=${CLUSTER}-private
              - --interval=${EXTERNALDNS_INTERVAL}
              - --log-format=text
              - --log-level=${EXTERNALDNS_LOG_LEVEL}
            envFrom:
              - secretRef:
                  name: external-dns-rfc2136-secret
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
    serviceAccount:
      create: false
      name: external-dns-rfc2136
    service:
      app:
        controller: external-dns-rfc2136
        ports:
          http:
            port: 7979
    serviceMonitor:
      app:
        serviceName: external-dns-rfc2136
        endpoints:
          - port: http
