---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-system

resources:
  - namespace.yaml
  - externalsecrets.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - monitoring
