---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dragonfly-operator
  labels:
    app.kubernetes.io/name: dragonfly-operator
spec:
  interval: 12h
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
  ref:
    tag: "v1.3.0"  # Exact version pinning
