apiVersion: v1
kind: Namespace
metadata:
  name: fluent-bit
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/component: workload
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: flux
  annotations:
    config.kubernetes.io/origin: workloads/platform/observability/fluent-bit