---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strimzi
  namespace: flux-system
  labels:
    app.kubernetes.io/name: strimzi-operator
spec:
  interval: 12h
  url: https://strimzi.io/charts/
  timeout: 3m
