---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: strimzi-operator-system

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
