---
apiVersion: v1
kind: Namespace
metadata:
  name: messaging
  labels:
    # Pod Security Admission - restricted for Kafka workloads
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

    # Standard labels
    app.kubernetes.io/name: messaging
    app.kubernetes.io/component: namespace
