---
# CiliumNetworkPolicy: Allow 1Password Connect access
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-1password-connect
spec:
  endpointSelector: {}
  egress:
  - toFQDNs:
    - matchPattern: opconnect.monosense.dev
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
