apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: networking

components:
  - ../../../../components/networkpolicy/deny-all
  - ../../../../components/networkpolicy/allow-dns
  - ../../../../components/networkpolicy/allow-kube-api
  - ../../../../components/networkpolicy/allow-internal
