---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pilar-runner-secret
  namespace: actions-runner-system
  labels:
    app.kubernetes.io/name: pilar-runner
    app.kubernetes.io/component: credentials
    app.kubernetes.io/part-of: actions-runner-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: ${EXTERNAL_SECRET_STORE}  # onepassword

  target:
    name: pilar-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        github_app_id: "{{ .github_app_id }}"
        github_app_installation_id: "{{ .github_app_installation_id }}"
        github_app_private_key: |
          {{ .github_app_private_key }}

  dataFrom:
    - extract:
        key: ${GITHUB_ARC_SECRET_PATH}  # kubernetes/apps/github-arc/auth
