apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system

resources:
  - fluent-bit/ks.yaml

commonLabels:
  app.kubernetes.io/part-of: observability
  app.kubernetes.io/managed-by: flux