---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging

resources:
  - kafka.yaml
  - kafka-nodepool.yaml
  - metrics-configmap.yaml
  - servicemonitors.yaml
  - prometheusrule.yaml
